### ISSUE TITLE
range of obfuscation

### ISSUE THREAD

**Issue by Sapu98** [Imprex-Development/orebfuscator#119]
It would be nice to be able to set the starting point of the obfuscation, like from y=30 to y=0, leaving everything above 30 clear.
(if it's already a thing, how do I do that?)

**Comment by Ingrim4** [comment]
Should this work independently for obfuscation and proximity hider or should the both share the same limit?

**Comment by Sapu98** [comment]
I'm not sure what does the proximity hider do, is it the thing that reveals near blocks when a player interacts with them?
if it is, it should be the same.
Now idk how does your code work but this is the idea:
```
int maxObfHeight = 30; //get this val from the plugin config
int minObfHeight = 10; //get this va from the plugin config
for(int i = minObfHeigh; i<maxObfHeight; i++ ){ 
obfuscate(x,i,z);
}
```

**Comment by Ingrim4** [comment]
I've come to the conclusion that it would make more sense to have them both separated since this would allow for more configuration. I will probably implement this in the next few days and add it to the next release.


P.S.
> I'm not sure what does the proximity hider do, is it the thing that reveals near blocks when a player interacts with them?

It's the thing that reveals obfuscated blocks once you get near them (you don't have to interact with them).
