### ISSUE TITLE
Feature: Geode hider

### ISSUE THREAD

**Issue by heathfx** [Imprex-Development/orebfuscator#130]
**Describe your feature**
If the proximity hider could interpolate "geode air" and fill it with deepslate or stone depending on y-level, would be really good to prevent users from cheating at finding geodes with freecam. The problem is that geodes leave a very recognizable shape in the ground even after hiding them based on proximity.

If I could hide an entire geode and fill it and surrounding structure-specific blocks with stone or deepslate (whichever is surrounding the geode) to a proximity of 10 blocks. It would make it very hard for players to cheat at finding these valuable structures.

Also disable revealing the geodes to spectators (disable revealing ore based on player's game mode).

**Comment by Ingrim4** [comment]
Your feature would suggest that Orebfuscator is able to detect structures like geodes and dungeons which it currently isn't. To be quiet honest I don't think that is something we will ever implement into Orebfuscator since it would invole looking at multiple chunks in the obfuscation step which is already very expesive on the hardware. So unless you have a better and less resource intensive soultion this sadly won't be part of Orebfuscator.
