### ISSUE TITLE
Orebfuscator throwing out errors in Console

### ISSUE THREAD

**Issue by MetalMinurz** [Imprex-Development/orebfuscator#131]
Orebfuscator recently began throwing out errors for one of my players, ~~and caused him to reach pings of 10000ms and lag out several times even after a server restart.~~

Here is the pastebin: https://pastebin.com/9NuN2RAP

**Comment by Ingrim4** [comment]
**Please fill out the following information:**

* Server Version: (use "/version" command for server version)
* Orebfuscator Version: (use "/version Orebfuscator" command for Orebfuscator version)
* Protocollib Version: (use "/version ProtocolLib" command for ProtocolLib version)

**Comment by MetalMinurz** [comment]
Apologies, the error was actually unrelated to the ping issue. Nevertheless, it still did create an error in console, albeit one that had no visible impact on the player.

Server Version: This server is running CraftBukkit version 3240-Spigot-6c1c1b2-332335e (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
Orebfuscator Version: Orebfuscator version 5.1.6
ProtocolLib Version: ProtocolLib version 4.7.0

**Comment by Ingrim4** [comment]
The error occurs whenever ChunkPackets are send but ProtocolLibs player instance is this a TemporaryPlayer. The TemporaryPlayer doesn't support permission requests hence why the error is "The method hasPermission is not supported for temporary players". I've looked a bit at ProtocolLibs implementation and I think I have two solutions: One would be to not request the permission from TemporaryPlayers this would result in the player always seeing the obfuscated chunks (since we can't test for the `orebfuscator.bypass`) until ProtocolLib has a real Player instance for us. The other one which is a little bit more complex would be to hold back chunk packets until ProtocolLib can provide the real Player instance. This would however be hard to test since I don't know how to force ProtocolLib to provide a TemporaryPlayer if not even impossible since I was never able to reproduce this in all the time I've been developing Orebfuscator. I will have to think about what solution I want to implement in the end.

**Comment by MetalMinurz** [comment]
Not sure if this matters, but I'm not actually using a dedicated permissions plugin. I'm using the bukkit permission system. There is also a plugin I'm using called "Plugin Hider Pro" (this seems like a bit of a stretch regarding the cause of the issue but I might as well mention it) which does block certain plugin packets from being sent to clients. Perhaps this is what's causing the problem? I'd do more testing on my side but I'm currently unable to access my server and am on mobile.

Anyways, thanks for taking a look at this bug for me! Really appreciate it.
