### ISSUE TITLE
Orebfuscator Lag Problem

### ISSUE THREAD

**Issue by giantfurkii** [Imprex-Development/orebfuscator#133]
**Please fill out the following information:**

* Server Version:  1.17.1
* Orebfuscator Version: 5.1.6
* Protocollib Version: 4.7.1 b531

**Describe the bug**

 The orebfuscator plug-in puts my server in the lag.
https://timings.aikar.co/?id=9e5b2770668049888d9a744f62a85b9c#plugins

**Comment by Ingrim4** [comment]
The high CPU-Usage is due to the fact that Orebfuscator is obfuscation all chunks that aren't in the cache on the main thread. This can't be changed since Minecraft only allows chunk access from the main thread. If you haven't already activeted the cache I would highly recommand you to do so otherwise the next update will add a hight limit option to the config which could shorten the obfuscation step signicatly base on your configuration. Another thing you could do to improve performance is to only use orebfuscator in worlds that really need to be obfuscated (maybe skip the end). Otherwise 7-8 ms per tick is to be expected with over 100 players. There is simply nothing we can do about it.

**Comment by giantfurkii** [comment]
As you can see, it puts a lot of strain on it.
![image](https://user-images.githubusercontent.com/78488589/133465293-f2ba07cf-d58a-4547-a828-d3b8f7179491.png)


But if I reduce the blocks in this part, for example, like a stone, the lag problem decreases.
![image](https://user-images.githubusercontent.com/78488589/133465484-1ea2404b-a9e9-4282-99b2-1b4e50612038.png)

I think the plugin has an optimization problem.
Do you have any suggested settings ?

**Comment by NgLoader** [comment]
We have found a new method to handle this issue

**Comment by Ingrim4** [comment]
We are currently investigating a possible major performance improvement which should affect almost every system.
