### ISSUE TITLE
No light data found for chunk...

### ISSUE THREAD

**Issue by Bobcat00** [Imprex-Development/orebfuscator#165]
**Please fill out the following information:**

* Server Version: git-Paper-404 (MC: 1.17.1)
* Orebfuscator Version: 5.2.1
* Protocollib Version: 4.7.0

**Describe the bug**

Using ViaVersion 4.1.1, if a player connects with a 1.18.1 client, the console occasionally shows the following warnings:
```
16:01:29 [WARN] [ViaVersion] No light data found for chunk at 1089, -897. Chunk was already loaded: false
16:01:29 [WARN] [ViaVersion] No light data found for chunk at 1105, -897. Chunk was already loaded: false
16:01:33 [WARN] [ViaVersion] No light data found for chunk at 1091, -922. Chunk was already loaded: false
16:01:33 [WARN] [ViaVersion] No light data found for chunk at 1107, -922. Chunk was already loaded: false
```
Myles from ViaVersion says this means a plugin is _"sending light in the wrong order."_ Further, he says, _"1.18 changed light data so it is rewritten by ViaVersion, it uses default light data when it can't find the data and produces that error."_

**If I remove Orebfuscator I don't see the error occurring.**

I can't narrow down the circumstances. It doesn't always occur for the same chunks. And I can fly through many chunks with no warnings, then get a bunch in a row. Clearing Orebfuscator's cache doesn't appear to affect the warnings.

**Comment by Bobcat00** [comment]
The Via* folks say to send the light data before the chunk/block data.
https://github.com/ViaVersion/ViaVersion/issues/2741#issuecomment-985003181

**Comment by Ingrim4** [comment]
Problem is that we don't touch the light packets, we only work with chunk packets. But chunk packets are handled async which means they are sent idepently of the light packets. Weird thing is since chunk packets are async they should always be sent after the light packet sometimes even multiple ticks later so I really don't know what the problem here is.

**Comment by Ingrim4** [comment]
What probably happens is the following:
- server sends light
- server sends chunk
- _orebfuscator starts processing chunk packet_
- server sends unlock chunk
- _orebfuscator sends processed chunk packet_

This would cause ViaVersion to store the light data  and delete it on chunk unload. Which in turn causes the delayed chunk packet to not contain any light data. Since the chunk is already unloaded this shouldn't cause any problems for your players but the error will remain. I'm still not sure if we will implement something to delay the chunk unload if a chunk is still processing. So for the moment you will have to live with the error in your console knowing that it doesn't affect your players.

**Comment by Bobcat00** [comment]
Ah, so the messages come from chunks which are unloaded? Sounds like it would be best to leave it alone (so they are unloaded) instead of delaying the unload. Server owners can put something in their log4j2.xml file to suppress the message from ViaVersion.

**Comment by Bobcat00** [comment]
> I'm still not sure if we will implement something to delay the chunk unload if a chunk is still processing.

How about not sending the processed chunk data if the chunk is no longer loaded?

**Comment by Ingrim4** [comment]
Would have the same complexity since I would have to keep track of all chunks that every player has loaded/unloaded and consecutively cancel the obfuscation task which isn't planned with the current way the plugin works.

**Comment by Bobcat00** [comment]
I submitted a PR to ViaVersion for them to simply allow server owners to suppress the meaningless warning message from spamming the console, but they won't do it.
https://github.com/ViaVersion/ViaVersion/pull/2795#issuecomment-1008310150

**Comment by Ingrim4** [comment]
I get what their saying technically this isn't their problem but ours. So they expect us to fix this. In a way this something I never planned on fixing but this probably needs fixing so expect an update in the next few week that will fix this behaviour.

**Comment by Bobcat00** [comment]
This took care of it:
`<RegexFilter regex="(^No light data found for chunk.*)" onMatch="DENY" onMismatch="ACCEPT"/>`

**Comment by kforbro** [comment]
> I get what their saying technically this isn't their problem but ours. So they expect us to fix this. In a way this something I never planned on fixing but this probably needs fixing so expect an update in the next few week that will fix this behaviour.

The issue is still there in 5.3.2 on the 1.16.5 server
![image](https://user-images.githubusercontent.com/39985355/207814993-f45f3794-6840-4021-9bf5-93bc519383e6.png)

**Comment by Bobcat00** [comment]
I'm not sure it really needs to be fixed. The message can be avoided with a plugin or the log4j2.xml file. I'm not sure if it even is a problem anymore. I'm not getting the messages on a Paper 1.19.2 server with 1.19.3 clients.

**Comment by kforbro** [comment]
> 

The problem is not in the message, but in the fact that chunks are loaded without light. This can be seen in the screenshot above

**Comment by Ingrim4** [comment]
I have honestly no idea how fix it properly without introducing new problems which is the main reason this hasn't be closed/fixed. I tried something on the [`165-stop-sending-unloaded-chunks`](https://github.com/Imprex-Development/Orebfuscator/compare/master...Imprex-Development:Orebfuscator:165-stop-sending-unloaded-chunks) branch but it didn't exactly work how it's supposed to work. The big problem is the asynchronicity of the whole networking system of the game and how to deal with it without creating race conditions and weird memory leaks. Therefor this will sadly have to stay in the mod since I have had no new ideas on how to fix it.

**Comment by Bobcat00** [comment]
Not to mention that Paper totally rewrote the chunk loading system.

**Comment by Leymooo** [comment]
That problem with chunks without lighting is that server continues to send LIGHT_UPDATE packets after it sends MAP_CHUNK packet (1.16.5 server, 1.18+ clients). 
![image](https://github.com/Imprex-Development/orebfuscator/assets/8667294/078bce50-d3c8-43ab-a303-20fad7ac0aa8)

When delaying MAP_CHUNK packet, ViaVersion will use data from the latest LIGHT_UPDATE packet (which looks like contains update only for specific chunk section instead for whole chunk) when sending delayed chunk.

So the current packet flow looks like this:
* server sends light - Via caches packet data
* server sends light - Via caches packet data (with overriding of previous data)
* server sends chunk -> orebfucator cancel packet
* server sends light - Via caches packet data (with overriding of previous data)
* server sends light - Via caches packet data (with overriding of previous data)
* server sends light - Via caches packet data (with overriding of previous data)
* orebfuscator sends chunk -> Via applies partial ligth data to chunk from latest light packet

Also AsyncPacketListener itself causes MAP_CHUNK packet to be out of order in cases when chunk should not be processed by orebfuscator (bypass perm or in ignored world).

For SyncPacketListener fix is trivial:
On MAP_CHUNK packet handling mark that chunk is currently being   obfucasting for player.
On UNLOAD_CHUNK abort chunk obfuscasting for player
On LIGHT_UPDATE if chunk is currenly being obfuscating,  cancel and put packet to delay queue for this chunk
When obfucasting is ready send MAP_CHUNK and then LIGHT_UPDATE packets from queue

For AsyncPacketListener maybe handling LIGHT_UPDATE also in async manner will put them in the right order.

**Comment by Leymooo** [comment]
> For AsyncPacketListener maybe handling LIGHT_UPDATE also in async manner will put them in the right order.

So, for Async Listener fix is much easier, just add these packets `UNLOAD_CHUNK`, `LIGHT_UPDATE`, `TILE_ENTITY_DATA` to listener, and ProtocolLib will properly put all them to right order. 

```java
	public ObfuscationListener(Orebfuscator orebfuscator) {
		super(orebfuscator, PacketType.Play.Server.MAP_CHUNK, Server.UNLOAD_CHUNK, Server.LIGHT_UPDATE, Server.TILE_ENTITY_DATA);
                .....
```	
```java
	@Override
	public void onPacketSending(PacketEvent event) {
		if (event.getPacket().getType() != Server.MAP_CHUNK) {
			return;
		}
                .....
```	

Looks like when doing `event.getAsyncMarker().incrementProcessingDelay();` for chunk packet, ProtocolLib queues all other packets  and waits for `this.asynchronousManager.signalPacketTransmission(event);` to transmit modiefied chunk packet and all next packets in rigth order. 

So the packet flow will look like this:

* server sends light - Via caches packet data
* server sends light - Via caches packet data (with overriding of previous data)
* server sends chunk -> orebfucator delays packet
* server sends light -> ProtocolLib queues packet
* server sends light  -> ProtocolLib queues packet
* server sends light  -> ProtocolLib queues packet
* orebfuscator sends chunk -> ViaVersion append correct ligth data to chunk -> ProtocolLib dequeue light packets -> Via caches packet data (with overriding of previous data)


This is how world looks like without these changes (1.16.5 server, 1.20.1 client):
![image](https://github.com/Imprex-Development/orebfuscator/assets/8667294/8682eb09-81d3-4dfc-9640-faad180c9e91)

And with these changes(sources before #270 pr merged (we are lazy to update configs))(No more dark chunks):
![image](https://github.com/Imprex-Development/orebfuscator/assets/8667294/0a5202eb-07ec-408e-ba63-4083c5b5570a)
![image](https://github.com/Imprex-Development/orebfuscator/assets/8667294/b7872c62-3aeb-4b54-a392-16dfe843f4e6)

**Comment by Bobcat00** [comment]
I haven't seen this happen on my server for a long time. I don't think it happens in 1.18.x, 1.19.x or 1.20.x. It may not be worth worrying about.

**Comment by Leymooo** [comment]
> I haven't seen this happen on my server for a long time. I don't think it happens in 1.18.x, 1.19.x or 1.20.x. It may not be worth worrying about.

I think this bug is only present on 1.18+ clients when running viaversion on 1.16 - 1.17.1 servers (maybe lower server versions are also affected).


This issue reveals problem with out of order of chunks packets, which potentially can cause some problems: 
* Clients (And viaversion caches) will have some chunks leaks. (Server sends unload chunk packets and later orebfuscator sends unloaded chunk to client, which will be never unloaded again).
* Server can send Tile Entity Update Packet assuming client have this chunk in memory but with orebfucator its can be not true. (Potentially some tile blocks may be missing/present  when should not be)
* Outdated lighting data on client
* Maybe something more

**Comment by Ingrim4** [comment]
Looks like a good fix to me. Just to be sure I also checked ProtocolLib's source to confirm they queue async packets in-order and only send a packet once all packets that got queued before that packet got send. Which for the most part happens [here](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/async/PacketSendingQueue.java#L140):

```java
        while (sending) {
            PacketEventHolder holder = sendingQueue.poll();

            if (holder != null) {
                sending = processPacketHolder(onMainThread, holder);

                if (!sending) {
                    // Add it back again
                    sendingQueue.add(holder);
                }

            } else {
```

Their technically is the rare case of some other plugin changing the sending order of packets but that's just something we have to live with. Once I add this to the master branch I will also deprecate the sync listener since that one is kind of hacky anyways and harder to fix (also don't think it's needed anymore). The way it works is, it straight up cancels the packets in a sync packet listener and re-queues them for sending once they are processed. So to solve them I would have to track the packet order myself which is pretty pointless since ProtocolLib already does it for me using an async listener.
