### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by yellow-pillow** [Imprex-Development/orebfuscator#186]
Hi, I've seen a lot of people suggest doing an entity anti xray

I propose to make it a separate project (plugin)
And I have an idea how to do it:
you can replace mobs with libs disguise for example with bats, which surely nobody wants))

this is possible? or it will create a big lag? interested in your opinion!)

**Comment by Ingrim4** [comment]
This still wouldn't eliminate the issue of detecting if the entity is visible to a player. Aside from that doing a distance based check would hinder the gameplay even more cause entities usually have a wide streaming distance and a tendency to move. The only reason we're even using the distance based proximity hider for blocks is because people usually remember where they placed a block (+ blocks can't move and are easy to hide/reveal).
