### ISSUE TITLE
Everything bugged, that could be bugged

### ISSUE THREAD

**Issue by cryofgaming** [Imprex-Development/orebfuscator#191]
### Description

So im using the latest "fix" for this plugin (https://github.com/Imprex-Development/Orebfuscator/issues/177#issuecomment-1013389079) but pretty much everything is broken, which could be broken.

- Players are invisible
- Items that got dropped are invisible
- Already dropped items, when collecting them, visible stay on the ground
- When you die, you cannot see your dropped items (but you can still collect them)

### Reproduction Steps

Just give a player some items, kill him and teleport him back to you

### Expected Behaviour

- Players visible
- Items that got dropped are visible
- Already dropped items, when collecting them, should get removed
- When you die, you should see your dropped items

### Server Details

Magma 1.12.2

### Orebfuscator Version

https://github.com/Imprex-Development/Orebfuscator/issues/177#issuecomment-1013389079

### ProtocolLib Version

4.4.0

### Logs and Configs

Default

**Comment by Ingrim4** [comment]
We can reproduce what you describe but are sadly unable to fix this as of now seeing as we have no time and other issues with a higher priority. We have however narrowed the issue down to the entity streaming range and the way Magma is sending items. This issue only occurs when the player is teleported which might indicate that Magma can't handle the async nature of Orebfuscator since Magma expects the chunks to be send immediately.

**Comment by MossCG** [comment]
pls try fix this, this problem exists on my servers these days

**Comment by NgLoader** [comment]
> pls try fix this, this problem exists on my servers these days

Can you please provide some more info?
- Server version:
- Orebufscator version:
- ProtocolLib version:
- Timings:

**Comment by Ingrim4** [comment]
Closed due to inactivity.
