### ISSUE TITLE
Low tps and Many Lag (Not Client)

### ISSUE THREAD

**Issue by IPECTER** [Imprex-Development/orebfuscator#201]
### Description

![image](https://user-images.githubusercontent.com/80433772/157038267-4fc8c0d5-0924-41c4-bc3b-d5ff95ec630e.png)
hmm....
https://timings.aikar.co/?id=079d6191299d4927b27d6a0ec0a4eddc
(already removed all air)

### Reproduction Steps

just use this plugin

### Expected Behaviour

lag

### Server Details

git-purpur-1566 1.18.1

### Orebfuscator Version

5.2.5

### ProtocolLib Version

4.8.0

### Logs and Configs

(already removed all air)

**Comment by IPECTER** [comment]
![image](https://user-images.githubusercontent.com/80433772/157040537-5a9bc323-d999-4f57-bb72-588bf488b2f8.png)

**Comment by Ingrim4** [comment]
Looks like your server can't load chunks fast enough. Normally this wouldn't be a problem because we limit the amount of ms per tick since version 5.2.2 of Orebfuscator to a default 10ms per tick. The way it works is we check every 4 chunks we loaded how much time it took and stop loading chunks if the threshold is reached. This would mean that your server needs on avg 224.16ms per four chunks which is odd. Maybe try running Orebfuscator without other plugins and see if it's still a problem. Their is nothing we can change in the code to improve performance in your case really sorry about that.
