### ISSUE TITLE
Light issue

### ISSUE THREAD

**Issue by Focxer** [Imprex-Development/orebfuscator#204]
### Description

Orebfuscator just screw up the light of my worlds, replacing illumination blocks cant fix it, when the server restarts... all goes black again

### Reproduction Steps

idk, i just download the plugin and boom, chunks goes dark

### Expected Behaviour

just hide blocks?!

### Server Details

git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Orebfuscator Version

5.2.6

### ProtocolLib Version

4.8.0

**Comment by Ingrim4** [comment]
Orebfuscator only manipulates chunk packets which contain no information about light which makes it impossible for Orebfuscator to break light on your server. My guess would be that your using other plugins that modify packets (which break because of Orebfuscator) or your world is weirdly pregenerated/edited.

**Comment by Ingrim4** [comment]
Will probably be fixed in the next update till then here's a pre-release version with the fix applied: https://github.com/Imprex-Development/Orebfuscator/suites/5686860028/artifacts/187003615

**Comment by Ingrim4** [comment]
Should be fixed as of #308
