### ISSUE TITLE
Delete unnecessary Listeners to optimize

### ISSUE THREAD

**Issue by KioProject123** [Imprex-Development/orebfuscator#210]
### Description

BlockPhysicsEvent is a heavy event, and the falling blocks will trigger EntityChangeBlockEvent too
EntityInteractEvent is a heavy event, and entity destroy blocks will trigger EntityChangeBlockEvent too
(Entity stepping on red stone ore will trigger a large number of EntityInteractEvent)

So there is no need for BlockPhysicsEvent and EntityInteractEvent to exist.

### Proposed Behaviour

.

**Comment by Ingrim4** [comment]
Thanks for the recommendation. We first added the BlockPhysicsEvent due to issue #202 which it turns out wasn't our fault but a bug in spigot [SPIGOT-6962](https://hub.spigotmc.org/jira/browse/SPIGOT-6962). Regarding the EntityInteractEvent we will remove it (as well as the BlockPhysicsEvent) since all usefull calls of the event get covered by the EntityChangeBlockEvent.
