### ISSUE TITLE
Wall hack bypass

### ISSUE THREAD

**Issue by TheUnsocialEngineer** [Imprex-Development/orebfuscator#225]
### Description

Meteor clients wall hack bypasses the ore obfuscation. only works for ores with exposed sides however this could still lead to veins of ore being found
![image](https://user-images.githubusercontent.com/96296891/176695209-70797578-5979-42b2-a028-79c9fb210b55.png)

### Reproduction Steps

Meteor client set wall hacks set the blocks shown in the image to translucent in the settings, head underground and activate it to see previously hidden ores.
![image](https://user-images.githubusercontent.com/96296891/176695652-700e70c5-9859-401a-9f03-a207c31d2b82.png)

### Expected Behaviour

ores  should be hidden however any ore with an exposed face within render is shown.

### Server Details

MC 1.18.2

### Orebfuscator Version

5.3.0

### ProtocolLib Version

Unable to gather as not admin on server.

**Comment by Ingrim4** [comment]
There is already a feature which can be enabled trough the  `useFastGazeCheck` setting inside a proximity config. I would however strongly advise to not use this since it's extremely resource intensive and optimized. We also don't plan on improving the feature since occlusion culling is more of GPU task then a CPU as far as I know.
