### ISSUE TITLE
What is the time of the cache config

### ISSUE THREAD

**Issue by mateuszanierusza** [Imprex-Development/orebfuscator#236]
### Description

In last days my server was working for 2 days and after about this time I have to always clear the cache manually in the orebfuscator_cache because there is a 8Gb used disk space from orebfuscator cache file. I want to know what is the values there. Is there write in KB, MB or GB and seconds, minutes or hours. Because I dont know how to setup this.

cache:
  enabled: true
  baseDirectory: orebfuscator_cache
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000
  maximumSize: 16384
  expireAfterAccess: 60000
  maximumTaskQueueSize: 32768

### Reproduction Steps

This doing automatically itself because whenever player walking on world the used space from orebfuscator cache goes up.

### Expected Behaviour

The server is shutting off because a low of disk space avaible

### Server Details

1.18.2 PaperSpigot

### Orebfuscator Version

5.3.0

### ProtocolLib Version

4.8.0

**Comment by NgLoader** [comment]
Checkout our [wiki](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#cache)

**Comment by Ingrim4** [comment]
`deleteRegionFilesAfterAccess` represents the milliseconds since the last time the file got accessed (read or write) meaning if the file got used in the last two days it won't be deleted. You can however set the time much lower, the internal scheduler tasked with the cleanup of files runs every hour meaning the lowest time that would make sense is one hour. This would however kind of the defeat the purpose of the cache which is why the value is by default that high. The next version of Orebfuscator will also offer an option to disable the disk cache completely without disabling the in memory cache.
