### ISSUE TITLE
Freecam deobfuscation issue

### ISSUE THREAD

**Issue by zPqguro03** [Imprex-Development/orebfuscator#242]
### Description

https://user-images.githubusercontent.com/20030855/189920462-0246194b-7eef-4560-9946-80809e0bdbd0.mp4

Using any hack client that has freecam, it is possible to de-obfuscate blocks by breaking them when used.
I tried to set up updateOnBlockDamage to false but the issue is not solved.

### Reproduction Steps

Download any hack client that has freecam (in the video i'm using MatHax).
The configuration is the following one: 
```
version: 2
general:
  checkForUpdates: true
  updateOnBlockDamage: false
  bypassNotification: true
  ignoreSpectator: false
  updateRadius: 1
advanced:
  verbose: false
  useAsyncPacketListener: true
  maxMillisecondsPerTick: 10
  protocolLibThreads: -1
  obfuscationWorkerThreads: -1
  proximityHiderThreads: -1
cache:
  enabled: true
  baseDirectory: orebfuscator_cache
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000
  enableDiskCache: true
  maximumSize: 16384
  expireAfterAccess: 60000
  maximumTaskQueueSize: 32768

...


proximity-overworld:
    enabled: true
    minY: 0
    maxY: 255
    worlds:
    - GenMap
    distance: 2
    useFastGazeCheck: false
    useBlockBelow: false
    hiddenBlocks:
      minecraft:white_stained_glass: {}
      minecraft:red_stained_glass: {}
      minecraft:orange_stained_glass: {}
      minecraft:pink_stained_glass: {}
      minecraft:yellow_stained_glass: {}
      minecraft:lime_stained_glass: {}
      minecraft:green_stained_glass: {}
      minecraft:light_blue_stained_glass: {}
      minecraft:cyan_stained_glass: {}
      minecraft:blue_stained_glass: {}
      minecraft:magenta_stained_glass: {}
      minecraft:purple_stained_glass: {}
      minecraft:brown_stained_glass: {}
      minecraft:gray_stained_glass: {}
      minecraft:light_gray_stained_glass: {}
      minecraft:black_stained_glass: {}
      minecraft:stone_bricks: {}
      minecraft:deepslate_bricks: {}
      minecraft:polished_blackstone_bricks: {}
      minecraft:deepslate_tiles: {}
    randomBlocks:
      minecraft:cracked_stone_bricks: 1
```

Place one of the blocks in the list of obfuscated blocks.
If you are close enough (4/5 blocks), you will be able to de-obfuscate the blocks by breaking them with the freecam.

### Expected Behaviour

In theory, it shouldn't happen that blocks are de-obfuscated if you're not close enough. In my case I set proximity distance: 2, but nevertheless it is possible to de-obfuscated them from further away

### Server Details

This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1) You are running the latest version Previous version: git-Paper-408 (MC: 1.17.1)

### Orebfuscator Version

5.3.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b577

### Logs and Configs

Config: https://gist.github.com/zPqguro03/3dd08a7157e9f1bb4dd764292fdb77ab

**Comment by Ingrim4** [comment]
First of all the `distance` setting in the proximity config is based on the player's position and movement and not any interaction with blocks.  Meaning if the distance of a player to an obfuscated block is less then the configured value the block will get deobfuscated. (From our wiki: `The proximity hider obfuscates surface-level blocks and reveals them to nearby players. This can be helpful since an anit-xray only obfuscates below surface-level blocks to create the illusion for non-xray players that their is no anti-xray.`)

Secondly the deobfuscation for every block that isn't proximity hidden works perfectly fine and doesn't deobfuscate blocks on interaction (as configured by yourself) unless they get broken which is intended.

Last but not least the server (minecraft server not any plugin) itself will send the correct block on interaction (such as breaking a block) no matter what you do. Meaning you need an anti cheat which is capable of blocking such packets from the server entirely. It is not the goal of Orebfuscator to filter invalid or ill intended packets. As such we will likely not change the current behavior.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
