### ISSUE TITLE
Some Deepslate ores are still visible.

### ISSUE THREAD

**Issue by Reiamsei** [Imprex-Development/orebfuscator#264]
### Description

When I have a good xray I can adjust which blocks are shown and which not. when i disable all blocks instead of the deepslate I can find diamond ores, redstone ores...

is there a way in the config to fix this ?

Because I can´t find anything wrong in it.

### Reproduction Steps

...

### Expected Behaviour

pls fix the deepslate ores

### Server Details

Paper 1.19.3

### Orebfuscator Version

5.3.2

### ProtocolLib Version

4.8.0

**Comment by Ingrim4** [comment]
You can configure blocks to be obfuscated in these two sections: [obfuscation config section](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section) and [proximity config section](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#proximity-config-section)

**Comment by Ingrim4** [comment]
The visible ores your talking about are probably all surface blocks (blocks that touch air) which get obfuscated by the proximity hider and deobfuscated if a player gets too close to them. There are two ways of fixing this either add all deepslate ores to the proximity hider but that would ruin the experience for the players since the could only see the ores if they're close enough which would result in them not finding as much ores (the legitimate way) or you could add all deepslate ores in the `randomBlocks` section in your obfuscation config section (which is what I would recommend). This will additionally fill the entire map with deepslate ores which will make it impossible for a simple x-ray to detect which blocks are real and which ones are fake.

Here an example config:
```yml
    randomBlocks:
      minecraft:stone: 15
      minecraft:deepslate: 15
      minecraft:cave_air: 5
      minecraft:diamond_ore: 10
      minecraft:deepslate_diamond_ore: 10
      minecraft:emerald_ore: 5
      minecraft:deepslate_emerald_ore: 5
      minecraft:gold_ore: 5
      minecraft:deepslate_gold_ore: 5
      minecraft:iron_ore: 5
      minecraft:deepslate_iron_ore: 5
      minecraft:copper_ore: 5
      minecraft:deepslate_copper_ore: 5
      minecraft:coal_ore: 5
      minecraft:deepslate_coal_ore: 5
      minecraft:lapis_ore: 5
      minecraft:deepslate_lapis_ore: 5
      minecraft:redstone_ore: 5
      minecraft:deepslate_redstone_ore: 5
      minecraft:cobblestone: 1
      minecraft:mossy_cobblestone: 1
      minecraft:obsidian: 1
      minecraft:tnt: 1
```
