### ISSUE TITLE
[Bug] Ghost-block if player spawns on top of a disquised block

### ISSUE THREAD

**Issue by CDAGaming** [Imprex-Development/orebfuscator#267]
### Description

A player in a server that I help manage had recently made the switch from Paper's Anti-Xray to using Orebfuscator, although one of our users has reported an issue of being stuck in mid-air after a warp (We have a home-like plugin, where players can store different home locations to warp to)

This is a clip comparison to represent the behavior exhibited:

Intended: https://medal.tv/games/minecraft/clips/TqePHNIliYhX2/d13375EChGUd?invite=cr-MSxPcGwsMzgyMDM5MDQs
Bugged: https://medal.tv/games/minecraft/clips/TA6Y6YSqaPzAW/d1337UtqHNna?invite=cr-MSxOM00sMzgyMDM5MDQs

From my perspective, In the 2nd clip, they spawned on top of a disguised block (In this case, a chest), where the client assumedly believed it was a full block when it isn't, causing then to never hit the ground to trigger the Spigot events to cause a cache update, until they hit said block causing a block update the other way. (I have not looked into the plugin's code to confirm this sequence of events, but this is how I believe it to be occuring)

### Reproduction Steps

- Place a chest in one location (Or presumably any disquised block that Orebfuscator effects)
- While the chunk containing this chunk is unloaded, and when the block is disquised (May need to disconnect after being a distance away, not too sure), teleport to the location directly above the chest
- You should experience a similar effect to https://medal.tv/games/minecraft/clips/TA6Y6YSqaPzAW/d1337UtqHNna?invite=cr-MSxOM00sMzgyMDM5MDQs

### Expected Behaviour

The user who located this issue displayed a follow-up clip, https://medal.tv/games/minecraft/clips/TqePHNIliYhX2/d13375EChGUd?invite=cr-MSxPcGwsMzgyMDM5MDQs (Of what is believed to be the intended behavior of chunk-loading beside disguised blocks)

### Server Details

Pufferfish version git-Pufferfish-56 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 950abff on HEAD)

### Orebfuscator Version

5.3.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b588

**Comment by Ingrim4** [comment]
This is indeed intended behavior. When I initially add the `useBlockBelowObfuscation` I already considered that happening and just brushed it off as being highly unlikely that a player gets stuck on proximity hidden blocks. My main argument for that thinking at time was that it's difficult to know when the block updates are safe to send so that the client doesn't simply ignore them which lead to the current solution which requires the player to move once. I don't known a better way of solving that but I will take a deeper look into the problem once I have more time (earliest next month).
