### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by Ksiedzu** [Imprex-Development/orebfuscator#273]
### Description

plugin not starting

### Reproduction Steps

i installed newest version of protocol and orebfuscator. it didnt work i downgraded for 5.2.5 and still same issue

### Expected Behaviour

if it's possible for it to work

### Server Details

This server is running Magma version 1.18.2-424e2e16 Cimplementing API version 1.18.2-R8.1-SNAPSHOT, Forge Version  48.2.1)

### Orebfuscator Version

5.2.5

### ProtocolLib Version

4.8.0

### Logs and Configs

https://pastebin.com/CrCEXsy0

**Comment by Ingrim4** [comment]
1. The version of Orebfuscator your using is outdated please use the latest version: https://github.com/Imprex-Development/orebfuscator/releases
2. The logs you provided only show an error on plugin shutdown (plugin automatically disables itself if an error occurred on startup) which isn't helpful since we need to know why the plugin didn't successfully start in the first place.

Please provide a full log of your server if the issue should persist after you update Orebfuscator.
