### ISSUE TITLE
Huge lags/crash servers

### ISSUE THREAD

**Issue by Kenjaca** [Imprex-Development/orebfuscator#288]
### Description

Hello,
Because players doesn't have respect, we need to put anti-cheats on our friendly server. But we still manage to get huge lags when connecting/tpa/home and also sometimes crash that we think it's coming from your plugin. So i may need your help to increase server stats on the config file. Also it's probably a dream, but i remember a way to configure orebfuscator so the fake-ores will only be next to ,player, surrounding them, and not being on all around chunks. Thanks you for reading and take time for me,
Cordially,
Kenjaca.

### Reproduction Steps

Just install the orebfuscator.

### Expected Behaviour

I want no more lags pls

### Orebfuscator Dump

https://gist.github.com/Kenjaca/ade757c352bd0d7d9820b019355b9ebd

### Extra Details

I just need someone or some people to answer my questions, first message on github, sorry for reporting this as a bug. Thank you.

**Comment by NgLoader** [comment]
Could you please provide a dump file?
You can create a dump file by running the command ``/orebfuscator dump``.
Additionally, please provide some timings by running ``/timings on``, waiting for some time (and generate load on the server while waiting e.g. teleporting moving around), and then running ``/timings paste`` to get the results.

**Comment by Kenjaca** [comment]
![Screenshot_317](https://user-images.githubusercontent.com/131828131/235243512-e1ac23c4-a26a-4abd-9a89-bb8bc4a6b7a3.png)
[DumpFile.zip](https://github.com/Imprex-Development/orebfuscator/files/11356965/DumpFile.zip)

This is on my "beta" server not on the real one where i had lags. Actually couldn't get anymore dump file on it because the plugin was make us to much crash so they decided to remove the plugin till we fix it.

**Comment by Ingrim4** [comment]
First of all I'm quite baffled how your using ProtocolLib v4.8.0 for a 1.19 server which shouldn't be possible maybe update that. Secondly could you maybe send the link to the timings since the screenshot isn't particularly helpful and please run timings for a longer time since your screenshot has a sample time of 3sec?

On another note have you tried running paper instead of spigot since as far as I can tell paper does a way better job of handling chunks in general.

**Comment by bobhenl** [comment]
https://spark.lucko.me/QMsVazuhVb I have to confirm this

**Comment by Ingrim4** [comment]
> https://spark.lucko.me/QMsVazuhVb I have to confirm this

I'm not quite sure what to do with the timings and how they relate to the original author/issue, but as far as your server goes Orebfuscator seems to be running fine with just 3.85% main thread usage and an overall system CPU usage of avg 60-75%. Meaning Orebfuscator isn't the main problem here because it mainly uses system CPU without generating load on the game threads. The timings you provided prove that with low main/game thread usage (3.85%) and the headroom on system CPU usage.

The parts that I marked red are Orebfuscator and the rest is the server itself and other plugins:
![grafik](https://user-images.githubusercontent.com/8127996/236651899-602a865c-a856-43ef-ab49-b6b410a03d4f.png)

I could probably also reduce the time Orebfuscator is currently using in the main thread by reducing the amount of thread park/unpark calls on worker threads through a rewrite of the task dispatcher but I don't think that would help your server with its performance/stability issues.

Also just noticed you have papers anti-xray enabled which also generates load on your server so you should definitely turn that off.

**Comment by bobhenl** [comment]
Thanks, I'll do. Also,can you please check this one? https://spark.lucko.me/rOIW8CvkDi There's 23% by Orebfuscator

**Comment by Kenjaca** [comment]
Hey,
I'm sorry that i let the github open but that wasn't orebfuscator causing us lags, that was the spiggot server it self, we changed it to a paper and we had no more lags. Thanks to all of your answer !
