### ISSUE TITLE
orebfuscator.bypass

### ISSUE THREAD

**Issue by Robo5626** [Imprex-Development/orebfuscator#293]
### Description

i dont know how to get it working got it added to my server but i dont know how to do this permission orebfuscator.bypass and where to put it could you help

### Reproduction Steps

i installed it added it to my server no issue started it and it didnt work 

### Expected Behaviour

install it and it work

### Orebfuscator Dump

[dump-2023-06-10_15.03.39.zip](https://github.com/Imprex-Development/orebfuscator/files/11712700/dump-2023-06-10_15.03.39.zip)

**Comment by NgLoader** [comment]
The ``orebfuscator.bypass`` permission will disable Orebfuscator (obfuscation and proximity) for the currently player who has the permission.

You can also checkout our [wiki](https://github.com/Imprex-Development/Orebfuscator/wiki/Permissions#permission)

**Comment by Robo5626** [comment]
Do I need it set to true

**Comment by Robo5626** [comment]
i set it to true it didnt work and also set it to false and still didnt work
do i need to do something in config

**Comment by Robo5626** [comment]
also did what the wiki said and it didnt work

**Comment by fesheath** [comment]
We have tried everything and it does not work, could you give us the full exact commands to use to type into the game to make it work.

**Comment by NgLoader** [comment]
Have you tryed to reconnect after changing the permission?

**Comment by fesheath** [comment]
yes ofcourse, we have tried everything we have thought of, commands, reconnect, server reboot, different gamemodes, different players.

**Comment by Robo5626** [comment]
yes we have still didnt work

**Comment by Ingrim4** [comment]
The default config is only setup for the default world names (world, world_nether, world_the_end). You have to add your world to the config, since your worlds have different names ('FlapJackSMP' & 'FlapJackSMP_nether'). Each obfuscation and proximity config has a `worlds` field which by default only contains the default world for said config (`world` for `obfuscation-overworld` & `proximity-overworld` and `world_nether` for `obfuscation-nether` & `proximity-nether`). So in total you have to edit the config in 4 different places for it to work.

**Comment by Robo5626** [comment]
oh ok thank you ill give it a try and see if it works

**Comment by fesheath** [comment]
Thank you so much, appreciate it, have a good day :p

**Comment by Robo5626** [comment]
worked thank you for your help :)
