### ISSUE TITLE
multiblock packete error

### ISSUE THREAD

**Issue by vaniron** [Imprex-Development/orebfuscator#324]
### Description

![image](https://github.com/Imprex-Development/orebfuscator/assets/17107410/98ade3be-3a13-4789-83be-06dd070b2aa5)
using latest dev build from github on 1.16.5

### Reproduction Steps

download latest artefact from github, use on 1.16.5

### Expected Behaviour

no errors?

### Orebfuscator Dump

https://gist.github.com/aglarcz/8561b27b586b766909836b1c7df044a3

**Comment by Ingrim4** [comment]
Seems to be an arclight only issue since it works perfectly fine for me using spigot 1.16.5 and considering arclight isn't a spigot fork that would be highly likely. Since we only support spigot and spigot forks this doesn't have the highest priority but I will see what I can do to fix it. If it's an easy fix will probably have this done before the next release (1.20.2).

**Comment by Ingrim4** [comment]
Can you confirm if the [latest dev build](https://github.com/Imprex-Development/orebfuscator/actions/runs/6319187745) fixed this issue for you? I would do it myself but I can't find the exact arclight version your using 1.16/1.0.25.

**Comment by vaniron** [comment]
Yes, working as intended on Arclight. Thanks for fix and sorry for late response.
