### ISSUE TITLE
Could the plugin add a feature for pie-chart jamming

### ISSUE THREAD

**Issue by Moranyixiao** [Imprex-Development/orebfuscator#341]
### Description

Minecraft pie chart are too overpowered for base greifing, could it be jammed using fake entity method?
it will be huge useful
https://feedback.minecraft.net/hc/en-us/community/posts/4410439326221-An-option-to-make-the-shift-F3-pie-chart-OP-only-on-servers
https://github.com/orbyfied/AntiPieRay

### Proposed Behaviour

Minecraft pie chart are too overpowered for base greifing, could it be jammed using fake entity method?
https://feedback.minecraft.net/hc/en-us/community/posts/4410439326221-An-option-to-make-the-shift-F3-pie-chart-OP-only-on-servers
https://github.com/orbyfied/AntiPieRay

**Comment by Ingrim4** [comment]
I don't think it's a good idea to generate a bunch of fake block entities since this will impact client performance and I can say from experience that a lot of people will have issue with that. My counter suggestion would be to simply use proximity hider to hide block entities that way you can't use x-ray or the F3 debug screen to check for block entities unless you get close to them and are looking directly at them.

**Comment by Moranyixiao** [comment]
i use the default setting of 
    distance: 24
    frustumCulling:
      enabled: true
      minDistance: 3.0
      fov: 80.0
on proximity but player can still use pie chart to detect entity block, should I change any setting?

**Comment by Ingrim4** [comment]
You could add all block entities to the `hiddenBlocks` section in your proximity config if you want to hide all of them. We aren't doing that already because it would limit players a lot since all blocks in their base would constantly be hide unless they get close to them.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
