### ISSUE TITLE
Invalid player data and close server

### ISSUE THREAD

**Issue by Coreli0** [Imprex-Development/orebfuscator#347]
### Description

If I join i have Invalid player data and server turns off.

### Reproduction Steps

Server 1.20.1 Spigot I use Viaversion and Viabackwards and I use cllient 1.20.1
1.Run server with orebfuscator
2.Try join
3.Server off

### Expected Behaviour

^

### Orebfuscator Dump

https://gist.github.com/Scorbunny10/8ed8042959b3f85e861c00cfb68cb581

**Comment by Ingrim4** [comment]
Could you please provide the error or if possible your entire log?

**Comment by Coreli0** [comment]
[crash-2024-01-31_15.14.38-server.txt](https://github.com/Imprex-Development/orebfuscator/files/14142468/crash-2024-01-31_15.14.38-server.txt)
@Ingrim4

**Comment by Ingrim4** [comment]
The error you send is related to ProtocolLib and not to Orebfuscator have you tried if the issue still persists if you remove Orebfuscator but not ProtocolLib?

**Comment by Coreli0** [comment]
Yes, I tried without Orebfuscator, I also had to generate a new world because I saw an error in the console that it was impossible to place a player and then it worked

**Comment by Ingrim4** [comment]
That is strange because I just check the whole stacktrace line by line and what I found out so far is that server sends a `PacketPlayOutLightUpdate` (light update) and ProtocolLib can't get the PacketType and throws an error. In this whole interaction isn't a single occurrence of Orebfuscator which is strange.

Is this the only error you getting or are there possibly some other errors? This could also be related to ViaVersion and/or ViaBackwards since both are known to no play nice with other packet modifying plugins. Did the user that caused the error use a different version than 1.20.1 (server version)?

**Comment by Coreli0** [comment]
I also had an error that you can't place a player. And the user who caused this error (me) was using the same version, 1.20.1.

**Comment by Ingrim4** [comment]
What do you mean with "place a player" because Orebfuscator doesn't have an error that sound anything like that? I'm pretty sure the problem is related to ViaVersion and ViaBackwards (because they made problems in the past) and it's hard to debug that since both change the protocol in a significant way. So I would recommend not using them and see if that fixes it.

**Comment by Coreli0** [comment]
@Ingrim4 I need both

**Comment by Coreli0** [comment]
I try without via plugins and and it works too

**Comment by Coreli0** [comment]
I found orebfuscator version working with via plugins https://github.com/FormallyMyles/Orebfuscator
