### ISSUE TITLE
Message getting spammed when block breaks.

### ISSUE THREAD

**Issue by steffqxyz** [Imprex-Development/orebfuscator#350]
### Description

There is a message that gets spammed for the whole server whenever someone breaks a block 

message: "someblock" contains "ore"

### Reproduction Steps

Break a block latest version

### Expected Behaviour

Not show a message in chat for everyone

### Orebfuscator Dump

https://gist.github.com/steffqxyz/e32ceaed5d301a875d7f454e9e6abc8f

**Comment by Ingrim4** [comment]
That's not us since the only messages we send are the following: [(found using github search)](https://github.com/search?q=repo%3AImprex-Development%2Forebfuscator%20sendMessage&type=code)
1. `sender.sendMessage("Incorrect command registered!");`
2. `sender.sendMessage("You don't have the 'orebfuscator.admin' permission.");`
3. `player.sendMessage("[§bOrebfuscator§f]§7 You bypass Orebfuscator because you have the 'orebfuscator.bypass' permission.");`
4. Update/Deprecation message which is only visible to admins (`orebfuscator.admin` permission) when they join the server.

Maybe another plugins that's not compatible with the chunks being "random"?

**Comment by Ingrim4** [comment]
Closed due to inactivity.
