### ISSUE TITLE
Internet band usage line overrun

### ISSUE THREAD

**Issue by ForClipso** [Imprex-Development/orebfuscator#351]
### Description

There is a lot of line usage on my server because of this plugin. I tried them all individually and this plugin increases it a little. I wonder if there is a performance or package problem in my configuration, could you please send me the optimised version. Sincerely.

![image](https://github.com/Imprex-Development/orebfuscator/assets/144541252/2e1214a9-f7e9-4d6c-8b7c-2812963dbe9f)

### Reproduction Steps

I download the plugin and install it on my server.
Internet band usage line rises.
I remove it from my server and the internet bandwidth usage line drops a little bit.

### Expected Behaviour

Not using too much internet bandwidth.

### Orebfuscator Dump

[Orebfuscator Dump](https://gist.github.com/ForClipso/69dae5df09b14cf2e4881c5641760760)
[Protocolib Dump](https://gist.github.com/ForClipso/2c6702e7be73f1013a9fa9ce1c72205f)
[Orebfuscator Config](https://gist.github.com/ForClipso/1c5702442f217065f66887395f7791f0)

**Comment by Ingrim4** [comment]
Chunk packets will get bigger since obfuscation is mostly random and increases the chunks block palette that is fact that I can't change. I however have added a new option in the latest version (5.4.3) called `layerObfuscation` (in the [`obfuscation`](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section) section) which in theory should improve packet sizes slightly. I also switched from sending single-block update packets to multi-block in the proximity hider which might also improve network usage.

**Comment by ForClipso** [comment]
> Chunk packets will get bigger since obfuscation is mostly random and increases the chunks block palette that is fact that I can't change. I however have added a new option in the latest version (5.4.3) called `layerObfuscation` (in the [`obfuscation`](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section) section) which in theory should improve packet sizes slightly. I also switched from sending single-block update packets to multi-block in the proximity hider which might also improve network usage.

Thank you for your help. Problem solved.
