### ISSUE TITLE
[!] Player managing to bypass certain minerals!

### ISSUE THREAD

**Issue by caiobarnes** [Imprex-Development/orebfuscator#356]
### Description

The player said he is using a client called 'toolbox' that can bypass certain ores, as shown in the video.

### Reproduction Steps

https://youtu.be/Pl-caMQtAqw

### Expected Behaviour

I hoped that wouldn't happen.

### Orebfuscator Dump

https://gist.github.com/caiobarnes/eab52d5d54d25b27d7ff1bee0a0b1198

**Comment by Ingrim4** [comment]
Seems like you modified your config or are using an older config since deepslate ores aren't used as obfuscation material making it easier for clients to find them. Either add them to your random blocks section or simply delete your config so Orebfuscator can generate an update to date config for you.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
