### ISSUE TITLE
Plugin doesn't obfuscates ores

### ISSUE THREAD

**Issue by 1lolplayer1** [Imprex-Development/orebfuscator#365]
### Description

it just does nothing world names are correct and it is enabled but still nothing

### Reproduction Steps

started server with plugin. I have proto and obfuscator but still doesn't obfuscates blocks
![image](https://github.com/Imprex-Development/orebfuscator/assets/126320304/d2619770-f6f7-45c7-bf8c-516cde952240)

### Expected Behaviour

I hope that this issue will be easy to fix

### Orebfuscator Dump

https://gist.github.com/1lolplayer1/2a346370ba596bf316a3fe04839aac6e

**Comment by Ingrim4** [comment]
Have you checked all of the points from our [common issue page](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#i-dont-see-any-blocks-obfuscated)?
 - Check that the player doesn't have the `orebfuscator.bypass` permission
 - Check if you have installed the latest version of [Orebfuscator](https://github.com/Imprex-Development/Orebfuscator/releases) and [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/) for your game version
 - Check if there are any warnings in the console about a wrongly configured config
 - Check if you used the correct world names in the config

Also please make sure you tested this on any of the configured worlds: `world`, `world_nether` or `world_the_end` because you also have a world named `Spawn` that isn't referenced anywhere in your config.

**Comment by 1lolplayer1** [comment]
It was because of permission I am admin :) thanks and sorry for disturbing.
