### ISSUE TITLE
Warn Spam when Moving into New Chunks

### ISSUE THREAD

**Issue by dekrypted** [Imprex-Development/orebfuscator#387]
### Description

When loading Chunks, the Console will be spammed with warns:
![image](https://github.com/user-attachments/assets/a80e4550-6351-4ecc-91b0-ee6478bedf43)

### Reproduction Steps

- Obfuscator v5.5.0
- Canvas 1.21 Build 596
- Load Chunks
- Check Console

### Expected Behaviour

For there not to be warns.

### Orebfuscator Dump

https://gist.github.com/dekrypted/4ceb9dfa1059b6bfbd4b61c99734a2d5

**Comment by dekrypted** [comment]
You guys aresoooo helpful. Switching back to paper

**Comment by Ingrim4** [comment]
Sorry about the delay—I've been pressed for time these past few weeks. Even if I had the time, we wouldn’t have fixed this. The Canvas authors decided to change a packet constructor overload to something so specific that it's impossible to create a decent/performant solution for it. And to be honest, I’m not going to spend time on a special fix for a Spigot fork that doesn't even show up in our [anonymous statistics](https://bstats.org/plugin/bukkit/Orebfuscator/8942). But hey, since this is FOSS, you're more than welcome to take a crack at it yourself—contributions are always appreciated!
