### ISSUE TITLE
Internal Exception: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by LukiEnLive** [Imprex-Development/orebfuscator#398]
### Description

I can't join the server when the plugin is on it. But for other players it works, they can join the server normally

### Reproduction Steps

Just add the plugin to the server regardless of the configuration. 
Some players will be able to access it normally, and others in my case will not be able to connect

### Expected Behaviour

I expect to be able to connect to the server 😅

### Orebfuscator Dump

Commands don't work, but i can give you the "disconnect" log txt, if thats can help.
![image](https://github.com/user-attachments/assets/d9373185-1784-4f88-a4b7-07c0e11490d9)
[disconnect-2024-11-09_23.37.25-client.txt](https://github.com/user-attachments/files/17689579/disconnect-2024-11-09_23.37.25-client.txt)

**Comment by Ingrim4** [comment]
Can you please provide us the whole server log as it looks like Orebfuscator isn't event running on your server (because the command isn't registered)?

**Comment by LukiEnLive** [comment]
Sure !
[latest.log](https://github.com/user-attachments/files/17700627/latest.log)

**Comment by Ingrim4** [comment]
Log looks fine without any obvious warnings, did you try to run the commands in the console, because the screenshot kind looks like it? If that's the case please retry the command without the `/` at the beginning as the console doesn't expect a `/` or you could alternatively run the command in-game and use the auto-suggestion to ensure you didn't do any typos.

**Comment by LukiEnLive** [comment]
[dump-2024-11-11_17.36.18.json](https://github.com/user-attachments/files/17706542/dump-2024-11-11_17.36.18.json)
i have the file !

**Comment by Ingrim4** [comment]
Everything looks normal are you sure Orebfuscator is the problem have you tried removing it to check if the issue still persists? 

The client error you initially provided is `Connection reset` which indicts a problem with your connection to the server (unrelated to plugins). Maybe the chunk packets are to big try to enable the `obfuscation.layerObfuscation` option to reduce the packet since.

**Comment by LukiEnLive** [comment]
"Everything looks normal are you sure Orebfuscator is the problem have you tried removing it to check if the issue still persists?"

yes the problem comes from the plugin because when I remove it without touching the rest of the configuration, everything works correctly. This is what I meant above with my sentence "Just add the plugin to the server regardless of the configuration."

"The client error you initially provided is Connection reset which indicts a problem with your connection to the server (unrelated to plugins)."

yes he says I have packet problems, which seems strange to me given that I have a good connection being fiber. But as said before since I have no problem without the plugin, it necessarily comes from the

"Maybe the chunk packets are to big try to enable the obfuscation.layerObfuscation option to reduce the packet since."

I just enabled the option for the 3 worlds and it seems that I no longer have the problem! I can connect to the worlds without any problem for the moment!
Just one last question, how can I test / be sure that the plugin works well?

**Comment by Ingrim4** [comment]
Use an X-Ray mod or [resource pack](https://www.curseforge.com/minecraft/texture-packs/xray-ultimate-1-11-compatible), make sure you don't have the `orebfuscator.bypass` permission and just see for yourself if you're still able to tell real and fake ores apart. [Here](https://github.com/Imprex-Development/Orebfuscator/wiki/Frequently-Asked-Questions#what-is-layerobfuscation-and-when-to-use-it) is an example image of what it should roughly look like.

If you have any issues seeing fake ores try our step by step guide in the [wiki](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#i-dont-see-any-blocks-obfuscated) and otherwise just ask for help in this issue.

**Comment by LukiEnLive** [comment]
Great thats work ! 
thanks for your time and this weird bug of paquets !
