### ISSUE TITLE
Proximity Hider problem

### ISSUE THREAD

**Issue by Bobcat00** [Imprex-Development/orebfuscator#55]
**Please fill out the following information:**
* Server Version: git-Spigot-57bbdd8-b8dd5ec (MC: 1.16.3) 
* Orebfuscator Version: 5.1.0
* Protocollib Version: 4.6.0-SNAPSHOT-b481

**Describe the bug**
If you join the server or teleport to within the Proximity Hider range of a block to be hidden (anvil, crafting table), the block will remain as stone no matter how you move.  Even if you move away from the block and back within Proximity Hider range, it remains as stone.

Also, plugin.yml has the version as 5.0.0, not 5.1.0.

**Comment by Ingrim4** [comment]
From the best I understand; that picture shows one of my players, a moment or two after he had logged in. Those stone blocks on the floor should be both some single block chest as well as a shulker or two. (if he were farther away then this would be no problem, but he's pretty close to em) but they are still 'stone' even though he is close to them.... Note: this problem seems to only be happening on the latest update to orebfuscator (5.1.0). I rolled back orebfuscator to (5.0.0) for the last 3 days and haven't heard any more complaints from my players. -- Please note: this is a superb plugin that literally saved my server. (anarchy server but with some anticheat) people couldn't hide anything because of stupid chest esp but this plugin stops that... well done 👍

_Originally posted by @Krater107a in https://github.com/Imprex-Development/Orebfuscator/issues/45#issuecomment-713169588_

**Comment by Ingrim4** [comment]
We found the cause of the problem and are currently working on a solution.
