### ISSUE TITLE
Worldguard flag

### ISSUE THREAD

**Issue by pintoso** [Imprex-Development/orebfuscator#94]
A flag for the worldguard to bypass proximity obfuscation.

the plugin is using resources in unnecessary places (spawns, lobbys, etc.) and it is also a bit annoying for new players to go to those places and have to get close to know which block is

**Comment by Ingrim4** [comment]
We don't have plans to implement this feature but feel free to fork us and do it yourself. 

The reason for not implementing this is that the cache wouldn't work anymore because every player would need his own version of a chunk packet because every player could have access to different regions. Another huge problem would be the enormous overhead involved with determining which block gets bypassed and which doesn't.

**Comment by pintoso** [comment]
makes sense
unfortunately I have no ideas on how to make this possible(without this problem)
anyway, thanks for the quick response ^^
