### ISSUE TITLE
Reload command

### ISSUE THREAD

**Issue by red40forever** [Imprex-Development/orebfuscator#95]
I asked about this in a review and it seems that the current solution is to /reload, which isn't ideal for some plugin combinations/configurations. This is a problem with my server specifically so it would be helpful to have a dedicated reload command to avoid the incompatibilities and overhead that comes with CraftBukkit's (or by extension, whatever API you're using).

Thank you.

**Comment by NgLoader** [comment]
You can use [Plugman](https://dev.bukkit.org/projects/plugman) to reload only one plugin.

**Comment by Ingrim4** [comment]
I've considered implementing a reload command but there are a few issues that would need fixing. First and foremost the config isn't hot swappable when the cache is enabled since everything async. This means we would have to stop all threads and restart them with the new config which is essentially what a bukkit reload does. Another problem which comes with the next release of OFC is that we then have an API that is dependand on the Cache, so we would need some sort of system to cache API calls while OFC is reloading (because a reload takes some time since the whole cache needs to be flushed to disk).
